scurry/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, BooleanField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    content = TextAreaField('Content', validators=[DataRequired()])
    private = BooleanField('Make Private')
    submit = SubmitField('Post') 

scurry/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from sqlalchemy import or_
from datetime import datetime
from flask_login import current_user, login_required
from scurry import db
from scurry.models import Post, User, PostShare
from scurry.posts.forms import PostForm

posts = Blueprint('posts', __name__)

@posts.route('/post', methods=['GET', 'POST'])
def new_post():
    postForm = PostForm()
    if postForm.validate_on_submit():
        post = Post(private=postForm.private.data, content=postForm.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Post Created!', 'success')
        return redirect(request.referrer)
    return render_template('post.html', title="Create Post", postForm=postForm)

@posts.route('/underground', methods=['GET', 'POST'])
@login_required
def underground():
    postForm = PostForm()
    if postForm.validate_on_submit():
        post = Post(private=postForm.private.data, content=postForm.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Post Created!', 'success')
        return redirect(request.referrer)
    page = request.args.get('page', 1, type=int)
    shared_posts = Post.query.filter(Post.shares) #.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    private_posts = Post.query.filter_by(private=True)
    posts = shared_posts.union(private_posts).order_by(Post.date_posted.desc(), Post.date_shared.desc()).paginate(page=page, per_page=5)
    return render_template('underground.html', title="Underground Feed", postForm=postForm, posts=posts)
 
@posts.route('/burrow', methods=['GET', 'POST'])
@login_required
def burrow():
    postForm = PostForm()
    if postForm.validate_on_submit():
        post = Post(private=postForm.private.data, content=postForm.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Post Created!', 'success')
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=current_user.username).first_or_404()
    posts = user.followed_posts().paginate(page=page, per_page=5)
    return render_template('burrow.html', postForm=postForm, title="My Burrow", posts=posts)

@posts.route('/like/<int:post_id>/<action>')
@login_required
def like_action(post_id, action):
    post = Post.query.filter_by(id=post_id).first_or_404()
    if action == 'like':
        current_user.like_post(post)
        db.session.commit()
    if action == 'unlike':
        current_user.unlike_post(post)
        db.session.commit()
    return redirect(request.referrer)

@posts.route('/post/share/<int:post_id>')
@login_required
def share_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author == current_user:
        flash('You can\'t share your own post', 'info')
        return redirect(request.referrer)
    if current_user.has_shared_post(post):
        flash('You have already shared this post', 'info')
        return redirect(request.referrer)
    current_user.share_post(post)
    post.date_shared = datetime.now()
    db.session.commit()
    flash('Post has been shared', 'success')
    return redirect(url_for('posts.underground'))

@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)
 
@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    postForm = PostForm()
    if postForm.validate_on_submit():
        post.content = postForm.content.data
        db.session.commit()
        flash('Post has been updated', 'success')
        return redirect(url_for('main.index'))
    elif request.method == 'GET':
        postForm.content.data = post.content
    return render_template('post.html', title='Update post', 
                            postForm=postForm)


@posts.route('/post/<int:post_id>/delete', methods=['POST', 'GET'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Post has been Deleted', 'success')
    return redirect(url_for('main.index'))

scurry/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from scurry import db, bcrypt
from scurry.models import User, Post
from scurry.users.forms import RegistrationForm, LoginForm, UpdateAccountForm
from scurry.users.utils import save_picture
from scurry.posts.forms import PostForm

users = Blueprint('users', __name__)

 
@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(
                username=form.username.data,
                email=form.email.data,
                password=hashed_password)
        db.session.add(user)
        db.session.commit()
        login_user(user)
        flash(f'Account created for {form.username.data}!', 'success')
        return redirect(url_for('main.index'))
    return render_template('register.html', title="Register", form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.index'))
        else:
            flash('Login Unsuccessful, please check credentials', 'danger')
    return render_template('login.html', title="Login", form=form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.login'))

# Get User Posts
@users.route('/user/<string:username>', methods=['GET', 'POST'])
def user_posts(username):
    postForm = PostForm()
    if postForm.validate_on_submit():
        post = Post(private=postForm.private.data, content=postForm.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Post Created!', 'success')
        return redirect(request.referrer)
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', postForm=postForm, posts=posts, user=user)

# Follow User
@users.route('/user/<string:username>/<action>')
def follow_action(username, action):
    user = User.query.filter_by(username=username).first_or_404()
    if action == 'follow':
        current_user.follow(user)
        db.session.commit()
    if action == 'unfollow':
        current_user.unfollow(user)
        db.session.commit()
    return redirect(request.referrer)


@users.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    accountForm = UpdateAccountForm()
    if accountForm.validate_on_submit():
        if accountForm.picture.data:
            picture_file = save_picture(accountForm.picture.data)
            current_user.image_file = picture_file
        current_user.username = accountForm.username.data
        current_user.email = accountForm.email.data
        db.session.commit()
        flash('Account has been updated!', 'success')
        return redirect(url_for('users.profile'))
    elif request.method == 'GET':
        accountForm.username.data = current_user.username
        accountForm.email.data = current_user.email
    postForm = PostForm()
    if postForm.validate_on_submit():
        post = Post(private=postForm.private.data, content=postForm.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Post Created!', 'success')
        return redirect(url_for('main.index'))
    image_file = url_for('static', filename='images/' + current_user.image_file)
    return render_template('profile.html', title="Profile", 
                            userForm=accountForm, postForm=postForm,
                            image_file=image_file)
 

scurry/templates/burrow.html
{% extends "layout.html" %}
{% block content %}
    <div class="container" id="home">
        <h1 class="page-header">My Burrow</h1>
        <p class="page-header">These are the posts hamsters you follow</p class="page-header">
        <div class="posts-container">
            {%  for post in posts.items %}
                <article class="article-post shadow">
                    <div class="post-head">
                        <img src="{{ url_for('static', filename='images/' + post.author.image_file) }}" alt="user photo" class="article-img">
                        <div class="post-metadata">
                            <a class="post-author" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                            <small>{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                            <p class="btn right">
                                <a href="{{ url_for('posts.like_action', post_id=post.id, action='like') }}" ><ion-icon name="thumbs-up"></ion-icon></a>
                                {{ post.likes.count() }}
                            </p>
                            <a href="{{ url_for('posts.share_post', post_id=post.id) }}" class="btn">
                                <ion-icon name="share-alt"></ion-icon>
                            </a>
                        </div>
                    </div>
                     
                    <div class="post-body">
                        <p class="post-content">{{ post.content }}</p>
                        <div class="post-buttons">
                            {% if current_user.username == post.author.username %}
                                <a href="{{ url_for('posts.update_post', post_id=post.id) }}" class="btn">Update</a>
                                <a href="{{ url_for('posts.delete_post', post_id=post.id) }}" class="btn">Delete</a>
                            {% endif %}
                        </div>
                    </div>
                </article>
            {% endfor %}
            <div class="pagination">
                {% for page_num in posts.iter_pages() %}
                    {% if page_num %}
                        <a class="btn btn-info" href="{{ url_for('main.index', page=page_num) }}">{{ page_num }}</a>
                    {% else %}
                        ...
                    {% endif %}
                {% endfor %}
            </div>
            
        </div>
    </div>
{% endblock content %}

scurry/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <div class="container" id="home">
        <h1 class="page-header">Above Ground Feed</h1>
        <p class="page-header subtext">These posts can be viewed by everyone</p>
        <div class="posts-container">
            {%  for post in posts.items %}
                <article class="article-post shadow">
                    <div class="post-head">
                        <img src="{{ url_for('static', filename='images/' + post.author.image_file) }}" alt="user photo" class="article-img">
                        <div class="post-metadata">
                            <a class="post-author" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                            <small>{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                            
                            <p class="btn right">
                                <a href="{{ url_for('posts.like_action', post_id=post.id, action='like') }}" ><ion-icon name="thumbs-up"></ion-icon></a>
                                {{ post.likes.count() }}
                            </p>
                            <a href="{{ url_for('posts.share_post', post_id=post.id) }}" class="btn">
                                <ion-icon name="share-alt"></ion-icon>
                            </a>
                            
                        </div>
                    </div>
                     
                    <div class="post-body">
                        <p class="post-content">{{ post.content }}</p>
                        <div class="post-buttons">
                            {% if current_user.username == post.author.username %}
                                <a href="{{ url_for('posts.update_post', post_id=post.id) }}" class="btn">Update</a>
                                <a href="{{ url_for('posts.delete_post', post_id=post.id) }}" class="btn">Delete</a>
                            {% endif %}
                            
                        </div>
                        
                    </div>
                </article>
            {% endfor %}
            <div class="pagination">
                {% for page_num in posts.iter_pages() %}
                    {% if page_num %}
                        <a class="btn btn-info" href="{{ url_for('main.index', page=page_num) }}">{{ page_num }}</a>
                    {% else %}
                        ...
                    {% endif %}
                {% endfor %}
            </div>
            
        </div>
    </div>
{% endblock content %}
{% block sidebar %}
    
{% endblock sidebar %}

scurry/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Custom Styles -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
    
    <!-- Title based on title variable from route -->
    {% if title %}
        <title>Scurry - {{ title }}</title>
    {% else %}
        <title>Scurry - A Place for Squirrels</title>
    {% endif %}
</head>
<body>
    <header>
        <nav class="header-nav">
            <div class="header-logo">
                <img src="{{ url_for('static', filename='images/scurry-logo.png') }}" alt="Scurry - A Place for Squirrels" class="logo">
                <!-- <p class="logo-text">Scurry</p> -->
            </div>
            <ul class="nav-list">
                <li class="nav-list-item">
                    <a href="{{ url_for('main.index') }}" class="nav-link">Above Ground Feed</a>
                </li>
            </ul>
            <ul class="nav-list right">
                {% if current_user.is_authenticated %}
                <li class="nav-list-item">
                    <a href="{{ url_for('posts.underground') }}" class="nav-link">Underground Feed</a>
                </li>
                <li class="nav-list-item">
                    <a href="{{ url_for('posts.burrow') }}" class="nav-link">My Burrow</a>
                </li>
                <li class="nav-list-item">
                    <a href="{{ url_for('users.profile') }}" class="nav-link">Profile</a>
                </li>
                <li class="nav-list-item">
                    <a href="{{ url_for('users.logout') }}" class="nav-link">Logout</a>
                </li>
                {% else %}
                <li class="nav-list-item">
                    <a href="{{ url_for('users.login') }}" class="nav-link">Login</a>
                </li>
                <li class="nav-list-item">
                    <a href="{{ url_for('users.register') }}" class="nav-link">Register</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </header>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{category}}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    <main id="main">
        <div class="content-container" id="main-block">
            {%  block content %}{% endblock %}
        </div>
        <div class="sidebar-container" id="sidebar-block">
        {% if current_user.is_authenticated %}
            <div class="home-sidebar-user-info">
                <img src="{{ url_for('static', filename='images/' + current_user.image_file) }}" alt="user photo" class="sidebar-img">
                <h2>{{ current_user.username }}</h2>
            </div>
            <div class="post-form">
                <form action="" method="POST" class="form">
                    <!-- csrf token tag -->
                    {{ postForm.hidden_tag() }}
                    <div class="form-legend">
                        <h1>New Post</h1>
                    </div>
                    <div class="form-well">
                        <div class="form-group">
                            {{ postForm.content.label(class="form-control-label") }}
                            {% if postForm.content.errors %}
                                <div class="invalid-feedback">
                                    {% for error in postForm.content.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ postForm.content(class="form-control-post-textarea") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ postForm.private.label(class="form-control-boolean-label") }}
                            {{ postForm.private(class="form-control-boolean") }}
                        </div>
                        <div class="form-group post-submit">
                            {{ postForm.submit(class="btn")}}
                        </div>
                    </div>
                </form>
            </div>

        {% else %}
            <div class="container" id="signup-card">
                <h1>Sign Up Today</h1>
                <a href="{{ url_for('users.register') }}"><button class="btn">Sign Up Here</button></a>
                <p>Or go to <a href="{{ url_for('users.login') }}">login</a></p>
            </div>
        {% endif %}
            {% block sidebar %}{% endblock %}
        </div>
    </main>

    <!-- Ion Icons script src -->
    <script src="https://unpkg.com/ionicons@4.5.10-0/dist/ionicons.js"></script>
</body>
</html>

scurry/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <form action="" method="POST" class="form">
        <!-- csrf token tag -->
        {{ form.hidden_tag() }}
        <div class="form-legend">
            <h1>Login</h1>
        </div>
        <div class="form-well">
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.submit(class="btn")}}
            </div>
        </div>
        <small>
            Don't Have An Account Yet? <a href="{{ url_for('users.register') }}" class="wrong-form">Register Here</a>
        </small>
    </form>
</div>
{% endblock content %}

scurry/templates/post.html
{% extends "layout.html" %}

scurry/templates/profile.html
{% extends "layout.html" %}
{% block content %}
    <div class="container" id="profile">
        <h1 class="page-header">This is the Profile page</h1>
        <div class="form">
            <form action="" method="POST" enctype="multipart/form-data">
                <!-- csrf token tag -->
                {{ userForm.hidden_tag() }}
                <fieldset class="form-group">
                    <div class="legend">
                        Account Info
                    </div>
                    <div class="form-group">
                        {{ userForm.username.label(class="form-control-label") }}

                        {% if userForm.username.errors %}
                            {{ userForm.username(class="form-control")}}
                            <div class="invalid-feedback">
                                {% for error in userForm.username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ userForm.username(class="form-control") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ userForm.email.label(class="form-control-label") }}
                        {% if userForm.email.errors %}
                            {{ userForm.email(class="form-control")}}
                            <div class="invalid-feedback">
                                {% for error in userForm.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ userForm.email(class="form-control") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ userForm.picture.label() }}
                        {{ userForm.picture(class="form-control-file") }}
                        {% if userForm.picture.errors %}
                            {% for error in userForm.picture.errors %}
                                <span class="text-danger">{{ error }}</span><br>
                            {% endfor %}
                        {%  endif %}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{ userForm.submit(class="btn btn-info")}}
                </div>
            </form>
        </div>
    </div>
{% endblock content %}
{% block sidebar %}

{% endblock sidebar %} 

scurry/templates/underground.html
{% extends "layout.html" %}
{% block content %}
    <div class="container" id="home">
        <h1 class="page-header">Your Underground Feed</h1>
        <p class="page-header">These posts are only shared with Scurry Users</p>
        <div class="posts-container">
            {%  for post in posts.items %}
                <article class="article-post shadow">
                    <div class="post-head">
                        <img src="{{ url_for('static', filename='images/' + post.author.image_file) }}" alt="user photo" class="article-img">
                        <div class="post-metadata">
                            <a class="post-author" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                            <small>{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                            
                            <p class="btn right">
                                <a href="{{ url_for('posts.like_action', post_id=post.id, action='like') }}" ><ion-icon name="thumbs-up"></ion-icon></a>
                                {{ post.likes.count() }}
                            </p>
                            <a href="{{ url_for('posts.share_post', post_id=post.id) }}" class="btn">
                                <ion-icon name="share-alt"></ion-icon>
                            </a>
                            
                        </div>
                    </div>
                     
                    <div class="post-body">
                        <p class="post-content">{{ post.content }}</p>
                        <br>
                        {% for shares in post.shares[-1:] | reverse %}
                        Post Shared By: <a class="post-author" href="{{ url_for('users.user_posts', username=shares.sharer.username) }}">{{shares.sharer.username}}</a>
                        
                            
                        {% endfor %}
                        <div class="post-buttons">
                            {% if current_user.username == post.author.username %}
                                <a href="{{ url_for('posts.update_post', post_id=post.id) }}" class="btn">Update</a>
                                <a href="{{ url_for('posts.delete_post', post_id=post.id) }}" class="btn">Delete</a>
                            {% endif %}
                        </div>
                    </div>
                </article>
            {% endfor %}
            <div class="pagination">
                {% for page_num in posts.iter_pages() %}
                    {% if page_num %}
                        <a class="btn btn-info" href="{{ url_for('main.index', page=page_num) }}">{{ page_num }}</a>
                    {% else %}
                        ...
                    {% endif %}
                {% endfor %}
            </div>
            
        </div>
    </div>
{% endblock content %}

scurry/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <h1>{{ user.username }}'s Posts</h1> <!--<h2>{{ posts.total }}</h2>-->
    <br><br>
    <a href="{{ url_for('users.follow_action', username=user.username, action='follow')}}" class="btn">Follow {{ user.followers.count() }}</a>
    <div class="posts-container">
        {%  for post in posts.items %}
            <article class="article-post shadow">
                <div class="post-head">
                    <img src="{{ url_for('static', filename='images/' + post.author.image_file) }}" alt="user photo" class="article-img">
                    <div class="post-metadata">
                        <a class="post-author" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                        <small>{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                        
                        <p class="btn right">
                            <a href="{{ url_for('posts.like_action', post_id=post.id, action='like') }}" ><ion-icon name="thumbs-up"></ion-icon> {{ post.likes.count() }}</a>
                            <!-- <p>Likes:</p> -->
                        </p>
                        <a href="{{ url_for('posts.share_post', post_id=post.id) }}" class="btn">
                            <ion-icon name="share-alt"></ion-icon>
                        </a>
                    </div>
                </div>
                    
                <div class="post-body">
                    <p class="post-content">{{ post.content }}</p>
                    <div class="post-buttons">
                        {% if current_user.username == post.author.username %}
                            <a href="{{ url_for('posts.update_post', post_id=post.id) }}" class="btn">Update</a>
                            <a href="{{ url_for('posts.delete_post', post_id=post.id) }}" class="btn">Delete</a>
                        {% endif %}
                        
                    </div>
                    
                </div>
            </article>
        {% endfor %}
        <div class="pagination">
            {% for page_num in posts.iter_pages() %}
                {% if page_num %}
                    <a class="btn btn-info" href="{{ url_for('main.index', page=page_num) }}">{{ page_num }}</a>
                {% else %}
                    ...
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}